let componentsDetails = [
	//CPU and CPU Fan
	{id:"CPU0", name:"CPU 0", category: "CPU", img:"cpu/cpu0_shelf.png", imgOffset:{x:-14, y:0}, dragImg:"cpu/cpu0_dragger.png", desc:"<p>A Land Grid Array processor with 8 cores and 16 threads. It runs at 3.5 GHz and supports a maximum memory rating of DDR4-3200. It fits an LGA 1151 socket.</p>", potentialDropTargets:["cpu"]},
	{id:"CPU1", name:"CPU 1", category: "CPU", img:"cpu/cpu1_shelf.png", imgOffset:{x:-8, y:-6}, dragImg:"cpu/cpu1_dragger.png", desc:"<p>A Pin Grid Array processor with 8 cores and 16 threads. It runs at 3.8 GHz and supports DDR RAM at 3200 MHz. It fits a PGA AM4 socket.</p>", potentialDropTargets:["cpu"]},
	{id:"CPU2", name:"CPU 2", category: "CPU", img:"cpu/cpu2_shelf.png", imgOffset:{x:-9, y:-7}, dragImg:"cpu/cpu2_dragger.png", desc:"<p>A Land Grid Array processor with 2 cores with 8 threads. It runs at 3.8 GHz and supports DDR4 memory at speeds up to 2133 MHz. It fits in an LGA 1151 socket.</p>", potentialDropTargets:["cpu"]},
	{id:"CPU3", name:"CPU 3", category: "CPU", img:"cpu/cpu3_shelf.png", imgOffset:{x:-17, y:-11.5}, dragImg:"cpu/cpu3_dragger.png", desc:"<p>A Pin Grid Array processor with 4 cores and 8 threads. It supports DDR3 memory up to 1866 MHz. It fits in a PGA AM3 socket.</p>", potentialDropTargets:["cpu"]},
	
	//RAM
	{id:"RAM0", name:"RAM Pack 0", category: "RAM", img:"ram/ram0_shelf.png", imgOffset:{x:2.5, y:14}, dragImg:"ram/ram0_dragger.png", desc:"<p>Contains two modules of DDR2-800 memory, each with a capacity of 2 GB. </p>", potentialDropTargets:["ramA", "ramB"]},
	{id:"RAM1", name:"RAM Pack 1", category: "RAM", img:"ram/ram1_shelf.png", imgOffset:{x:3.5, y:14}, dragImg:"ram/ram1_dragger.png", desc:"<p>Contains two modules of DDR3-1400 memory, each with a capacity of 2 GB.</p>", potentialDropTargets:["ramA", "ramB"]},
	{id:"RAM2", name:"RAM Pack 2", category: "RAM", img:"ram/ram2_shelf.png", imgOffset:{x:2.25, y:14}, dragImg:"ram/ram2_dragger.png", desc:"<p>Contains two dual inline memory modules, each with a capacity of 2 GB. These modules are in a DDR4 format and run at 1866 MHz.</p>", potentialDropTargets:["ramA", "ramB"]},
	{id:"RAM3", name:"RAM Pack 3", category: "RAM", img:"ram/ram3_shelf.png", imgOffset:{x:2.5, y:14}, dragImg:"ram/ram3_dragger.png", desc:"<p>Contains two memory modules of DDR4 RAM that run at 2600 MHz, each with a capacity of 4GB. </p>", potentialDropTargets:["ramA", "ramB"]},
	{id:"RAM4", name:"RAM Pack 4", category: "RAM", img:"ram/ram4_shelf.png", imgOffset:{x:3, y:14}, dragImg:"ram/ram4_dragger.png", desc:"<p>Contains two memory modules of DDR4-3200 RAM, with a total capacity of 16 GB. This RAM is installed in a single-channel configuration.</p>", potentialDropTargets:["ramA", "ramB"]},
	{id:"RAM5", name:"RAM Pack 5", category: "RAM", img:"ram/ram5_shelf.png", imgOffset:{x:3, y:14}, dragImg:"ram/ram5_dragger.png", desc:"<p>Contains two memory modules of DDR4-3200 RAM, with a total capacity of 16 GB. This RAM is installed in a dual-channel configuration.</p>", potentialDropTargets:["ramA", "ramB"]},	

	//GPU	
	{id:"GPU0", name:"GPU 0", category: "GPU", img:"gpu/gpu0_shelf.png", imgOffset:{x:-30, y:-8}, dragImg:"gpu/gpu0_dragger.png", desc:"<p>A graphics card  with 512 MB of GDDR2 memory and a PCI connection. Available monitor connections are DVI/D, S-Video and VGA.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC"]},
	{id:"GPU1", name:"GPU 1", category: "GPU", img:"gpu/gpu1_shelf.png", imgOffset:{x:-19, y:2.25}, dragImg:"gpu/gpu1_dragger.png", desc:"<p>A graphics card  with 2 GB of GDDR4 memory. It has a PCIe x16 connection and a low-profile form factor. Available monitor connections are a single HDMI port and a single display port.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC"]},
	{id:"GPU2", name:"GPU 2", category: "GPU", img:"gpu/gpu2_shelf.png", imgOffset:{x:-20, y:0}, dragImg:"gpu/gpu2_dragger.png", desc:"<p>A graphics card with 4 GB of GDDR4 memory. It has a PCIe x16 connection and two HDMI ports, one display port, and one DVI-D port. It can only support two monitors if it uses the HDMI ports simultaneously.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC"]},
	{id:"GPU3", name:"GPU 3", category: "GPU", img:"gpu/gpu3_shelf.png", imgOffset:{x:-15, y:-8}, dragImg:"gpu/gpu3_dragger.png", desc:"<p>A graphics card  with 8 GB of GDDR6 memory. It has a PCIe x16 connection, three HDMI ports and three display ports. It requires an 8-pin power connection to the PSU. It can support up to three monitors simultaneously.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC", "cardWide"]},	

	//Expansion Cards/Other Types of Cards
	{id:"Card0", name:"EXP Card 0", category: "Cards", img:"cards/card0_shelf.png", imgOffset:{x:-66, y:-2}, dragImg:"cards/card0_dragger.png", desc:"<p>A network interface card capable of bandwidth up to 1 GB/s. It uses a PCIe x4 slot.</p>", potentialDropTargets:["cardNarrowA", "cardNarrowB"]},
	{id:"Card1", name:"EXP Card 1", category: "Cards", img:"cards/card1_shelf.png", imgOffset:{x:-66, y:-2}, dragImg:"cards/card1_dragger.png", desc:"<p> A network interface card that connects using a PCIe x4 slot. It has a maximum bandwidth of 10 GB/s.</p>", potentialDropTargets:["cardNarrowA", "cardNarrowB"]},
	{id:"Card2", name:"EXP Card 2", category: "Cards", img:"cards/card2_shelf.png", imgOffset:{x:-21, y:-4}, dragImg:"cards/card2_dragger.png", desc:"<p> An audio card with surround sound connections, as well as a microphone input. It connects to a PCI slot.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC"]},
	{id:"Card3", name:"EXP Card 3", category: "Cards", img:"cards/card3_shelf.png", imgOffset:{x:-21, y:-2.5}, dragImg:"cards/card3_dragger.png", desc:"<p>An expansion card with four USB 2.0 ports. It connects using a PCI slot.</p>", potentialDropTargets:["cardWideA", "cardWideB", "cardWideC"]},
	{id:"Card4", name:"EXP Card 4", category: "Cards", img:"cards/card4_shelf.png", imgOffset:{x:-66, y:-2}, dragImg:"cards/card4_dragger.png", desc:"<p>This card provides five ports using the USB 3.2 standard. It connects using a PCIe x4 slot.</p>", potentialDropTargets:["cardNarrowA", "cardNarrowB"]},
	
	//Hard Drives
	{id:"Drive0", name:"Drive 0", category: "Drives", img:"drives/drive0_shelf.png", imgOffset:{x:7.5, y:5.5}, dragImg:"drives/drive0_dragger.png", desc:"<p>A 3.5″ hard disk drive with a speed of 5,400 RPM. It has a capacity of 250 GB and connects using an EIDE parallel connection.</p>", potentialDropTargets:["driveBay"]},
	{id:"Drive1", name:"Drive 1", category: "Drives", img:"drives/drive1_shelf.png", imgOffset:{x:7.5, y:4.25}, dragImg:"drives/drive1_dragger.png", desc:"<p>A hard disk drive with a 3.5″ form factor and a capacity of 1,000 GB. It connects using a serial ATA bus and spins at 5,400 RPM. </p>", potentialDropTargets:["driveBay"]},
	{id:"Drive2", name:"Drive 2", category: "Drives", img:"drives/drive2_shelf.png", imgOffset:{x:7.5, y:4.25}, dragImg:"drives/drive2_dragger.png", desc:"<p>A 4 TB hard disk drive that connects via SATA and fits a 3.5″ drive bay. It rotates at a speed of 7,200 RPM.</p>", potentialDropTargets:["driveBay"]},
	{id:"Drive3", name:"Drive 3", category: "Drives", img:"drives/drive3_shelf.png", imgOffset:{x:7.5, y:4.25}, dragImg:"drives/drive3_dragger.png", desc:"<p>A hard disk drive that fits into a 3.5″ drive bay. It will hold up to 4 TB of data, connects to the serial ATA bus, and has a speed of 10,000 RPM. </p>", potentialDropTargets:["driveBay"]},

	//Power Supply Connectors
	{id:"24pin", name:"24-Pin ATX Power Connector", category: "PSC", img:"psc/24pin_atx_power_connector.png", desc:"<p>This power connection supplies 12V, 5V and 3.3V power to the motherboard.</p>", connectionType:"partial", fixedStart:"powerSupply", permittedTargets:["24pin", "powerSupply"]},	
	{id:"68pin", name:"6/8-Pin ATX Power Connector", category: "PSC", img:"psc/6_8pin_atx_power_connector.png", desc:"<p>This connector provides power to some expansion cards and the GPU card, as necessary.</p>", connectionType:"partial", fixedStart:"powerSupply", permittedTargets:["68pin", "powerSupply"]},
	{id:"4pin", name:"4-Pin ATX Power Connector", category: "PSC", img:"psc/4pin_atx_power_connector.png", desc:"<p>This connector typically supplies power to the CPU through the motherboard.</p>", connectionType:"partial", fixedStart:"powerSupply", permittedTargets:["4pin", "powerSupply"]},
	{id:"sataPower", name:"SATA Power Connector", category: "PSC", img:"psc/sata_power_connector.png", desc:"<p>This connector supplies power to modern peripheral devices inside the computer.</p>", connectionType:"partial", fixedStart:"powerSupply", permittedTargets:["driveSATA", "powerSupply"]},
	{id:"molex", name:"Molex Connector", category: "PSC", img:"psc/molex_connector.png", desc:"<p>This connector delivers power to older devices used inside older computers.</p>", connectionType:"partial", fixedStart:"powerSupply", permittedTargets:["driveMolex", "powerSupply"]},	
	
	//Front Panel Connectors
	{id:"fpcHarness", name:"Front Panel Connector Cluster", category: "FPC", img:"fpc/front_panel_connectors.png", desc:"<p>A cluster of four cables:</p><ul><li>Power (PWR) – Connects the power button on the case to the motherboard, allowing the user to turn on the computer.</li><li>Speaker (SPKR) – Connects the case speaker to the motherboard for system sounds, such as POST beep codes.</li><li>HDD LED (HDDLED) – Connects an LED on the case that verifies hard disk drive usage to the motherboard.</li><li>Power LED (PWRLED) – Controls an LED on the case which verifies that the system is powered on.</li></ul>", connectionType:"partial", fixedStart:"fpcHarness", permittedTargets:["fpc", "fpcHarness"]},
		
	//Other Connectors
	{id:"edie", name:"EDIE Data Connector", category: "OC", img:"oc/edie_data_connector.png", desc:"<p>This 40-pin ribbon cable can connect one or two drives to a motherboard in a parallel connection.</p>", connectionType:"full", permittedTargets:["driveDataEDIE", "driveMolex", "driveSATA"]},
	{id:"sataData", name:"SATA Data connector", category: "OC", img:"oc/sata_data_connector.png", desc:"<p>This cable is used to transmit data between the motherboard and SATA storage devices.</p>", connectionType:"full", permittedTargets:["driveDataSATA", "driveMolex", "driveSATA"]},
	{id:"chassisFan", name:"Chassis Fan Connector (3-pin)", category: "OC", img:"oc/chassis_fan_connector_3_pin.png", desc:"<p>This connector provides power to a chassis fan to cool the computer.</p>", connectionType:"partial", fixedStart:"chassisFan", permittedTargets:["chassisPower", "chassisFan"]},
	{id:"cpuFan", name:"CPU Fan Connector", category: "OC", img:"oc/cpu_fan_connector.png", desc:"<p>his connector provides power to a fan that specifically services the CPU to remove heat from the processor.</p>", connectionType:"partial", fixedStart:"cpuFan", permittedTargets:["cpuPower", "cpuFan"]}
]